environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@latest -g
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build

build: off

version: "{build}"
